- ui/languages
> Proposed corrected label for lzh

- src/gnome2/main_window.c
> Fixed issue #810

- .travis.yml
- tests/travis/build_linux.sh
Adds a test for building in Debian's sid environment
> Add testing in Debian sid

- po/it.po
I translated till 50%, I will finish it an other time.
> Up to 50% of the translation

- src/gnome2/navbar_versekey.c
- ui/navbar_versekey.gtkbuilder
Delete duplicate arrows on navbar_versekey and show that they exist only for visual effects.
> remove repeated arrow display

- po/zh_CN.po
- src/gnome2/find_dialog.c
> find dialog has an unknown button

- src/gnome2/font_dialog.c
> fixed gtk_font_button_get(set)_font_name deprecated

- ui/navbar_versekey.gtkbuilder
> use glade to rewrite file, and remove gtk deprecation property

- src/gnome2/dictlex.c
- src/gnome2/navbar_book.c
- src/gnome2/navbar_book_dialog.c
- src/gnome2/navbar_versekey_dialog.c
- src/gnome2/navbar_versekey_editor.c
- src/gnome2/navbar_versekey_parallel.c
> fixed gtk_menu_popup_at_widget call

- src/gnome2/navbar_versekey.c
fixed bug #881, and maybe #844, please review.
> fixed bug #881

- .travis.yml
* Use Official Docker image
* Fix required package list
* Re-include in per-distro Biblesync source install
> Fix Arch Linux Docker setup

- .travis.yml
Fixes the Archlinux test build.
> Fix Arch build

- po/bg.po
- po/my.po
This is an update of two locale, my had sometimes @@@ instead of text! And parts of the bg text were badly encoded (a residue from an old translation?)
> Locale my and bg updated

- .travis.yml
- cmake/XiphosDependencies.cmake
- src/gtk/utilities.c
Fixes build errors related to minizip - doesn't seem to write the files properly, though.
> Fix build errors for minizip

- .github/workflows/builds.yml
- win32/WindowsBuildNotes.txt
- win32/xc-xiphos-win.sh
Converts win32 build script to run directly on any host/container, including directions on how to run it.
> Win32 builds

- po/POTFILES.in
- po/POTFILES.skip
- po/fr.po
- po/xiphos.pot
- src/gtk/dialog.c
- src/main/search_dialog.cc
- ui/gtk2_webedit.ui
- ui/gtk_webedit.ui
- ui/search-dialog.glade
- ui/search-dialog.gtkbuilder
- ui/xi-export-bookmarks.glade
- ui/xi-menus-popup.gtkbuilder
- ui/xi-menus.glade
This pull request is a update of the French translation. I made some corrections in the code to make the text more relevant.
About the pot file, I have not the string of the desktop shortcut. I have no idea why?
> New French translation with pot regenerated and minor typo correction

- po/cs.po
> Czech translation update

- po/da.po
- Fixed lots of typos
- Fixed a lot of wrong translations; where the source and target didn't say remotely the same thing
- Translated untranslated strings
> Updated the danish translation

- src/gtk/preferences_dialog.c
> properly close preferences dialog on escape key

- .ci-build.yml
- .github/dependabot.yml
- .github/workflows/builds.yml
- CMakeLists.txt
- INSTALL.md
- cmake/XiphosDependencies.cmake
- win32/Dockerfile
- win32/build_sword.sh
- win32/xc-xiphos-win.sh
A manual update of the GHA pins so that we can get Actions running again Also, enable dependabot so that we can auto-update the pins in the future
Fixes #1190
> Add dependabot and update actions

- .github/workflows/builds.yml
- src/backend/CMakeLists.txt
- src/editor/CMakeLists.txt
- src/gtk/CMakeLists.txt
- src/main/CMakeLists.txt
- src/webkit/CMakeLists.txt
- src/xiphos_html/CMakeLists.txt
- win32/build_sword.sh
Only link to PkgConfig::WK if it was discovered
Name Windows artifacts differently
> Finalize Windows build

- .github/workflows/builds.yml
- win32/CMakeLists.txt
- win32/build_sword.sh
Build more things directly in the GitHub Actions
Add more target configurations to the matrix
> Consolidate build logic
